INSERT INTO UNIDADE VALUES (1, 'Unidade Zona Sul', 'Avenida Cavalhada, 1054');

INSERT INTO CLIENTE VALUES (null, 'Fulano da Silva', '000.111.222-33', FALSE, 1);
INSERT INTO CLIENTE VALUES (null, 'Ciclano Santos', '111.222.333-44', TRUE, 1);

INSERT INTO ANIMAL (CLIENTE_ID, DATA_NASCIMENTO, ESPECIE, NOME, UNIDADE_ID) VALUES (1, '2019-01-02', 'MAMIFERO', 'Totó', 1);
INSERT INTO ANIMAL (CLIENTE_ID, DATA_NASCIMENTO, ESPECIE, NOME, UNIDADE_ID) VALUES (2, '2016-07-31', 'REPTIL', 'Rex', 1);