create table tb_animal (
codigo BIGINT generated by default as identity,
client_id BIGINT,
data_nascimento DATE,
especie VARCHAR2(10),
nome VARCHAR2(100),
primary key (codigo)
);

CREATE TABLE TB_CLIENTE (
 ID BIGINT generated by default as identity,
 NOME_CLIENTE VARCHAR2(100),
 CPF_CLIENTE VARCHAR2(14),
 INADIMPLENTE BOOLEAN,
primary key (ID)
);