INSERT INTO UNIDADE
VALUES (1, 'Cristóvão', 'Rua Cristóvão Colombo');

INSERT INTO UNIDADE
VALUES (2, 'Centro', 'Rua Alberto Bins');

INSERT INTO UNIDADE
VALUES (3, 'Zona Sul', 'Rua Mario Totta');

INSERT INTO CLIENTE 
VALUES (1, 'Fulano Silva', '111.222.333-44', TRUE, 1);

INSERT INTO CLIENTE 
VALUES (2, 'Ciclano Silva', '111.222.333-55', TRUE, 2);

INSERT INTO ANIMAL (CLIENTE_ID, DATA_NASCIMENTO, ESPECIE, NOME, UNIDADE_ID)
VALUES (1, '2019-01-02', 'MAMIFERO', 'Pluto', 1);

INSERT INTO ANIMAL (CLIENTE_ID, DATA_NASCIMENTO, ESPECIE, NOME, UNIDADE_ID)
VALUES (2, '2017-01-03', 'MAMIFERO', 'Pluto', 2);

INSERT INTO ANIMAL (CLIENTE_ID, DATA_NASCIMENTO, ESPECIE, NOME, UNIDADE_ID)
VALUES (2, '2016-06-22', 'MAMIFERO', 'Rex', 2);